In [2]:
import numpy as np

image = np.array([
    [100, 102, 101, 103, 100],
    [101,  99, 255, 102, 101],
    [100, 101, 100,  99, 102],
    [102, 100,  98, 101, 100],
    [101, 103, 100, 102,  99]
], dtype=np.float32)

In [3]:
a = np.zeros((3, 3), dtype=np.float32)

for y in range(3):
    for x in range(3):
        total = 0

        for i in range(3):
            for j in range(3):
                total += image[i + y][j + x]

        a[y][x] = total / 9

print(a)

[[117.666664 118.       118.111115]
 [117.333336 117.22222  117.55556 ]
 [100.55556  100.44444  100.111115]]


In [4]:
neighborhood = image[0:3, 1:4]

kernel = np.ones((3, 3), dtype=np.float32) / 9

weighted_values = neighborhood * kernel

result = np.sum(weighted_values)

print("Neighborhood:")
print(neighborhood)

print("\nKernel:")
print(kernel)

print("\nAfter multiplication:")
print(weighted_values)

print("\nFinal result:")
print(result)

Neighborhood:
[[102. 101. 103.]
 [ 99. 255. 102.]
 [101. 100.  99.]]

Kernel:
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]

After multiplication:
[[11.333333 11.222222 11.444445]
 [11.       28.333334 11.333333]
 [11.222222 11.111112 11.      ]]

Final result:
118.0


In [6]:
import numpy as np

image = np.array([
    [10,  20,  30,  40,  50],
    [60,  70,  80,  90, 100],
    [110, 120, 130, 140, 150],
    [160, 170, 180, 190, 200],
    [210, 220, 230, 240, 250]
], dtype=np.float32)

kernel = np.array([
    [0, 0, 0],
    [0, 1, 0],
    [0, 0, 0]
], dtype=np.float32)

In [7]:
image_height, image_width = image.shape

kernel_height, kernel_width = kernel.shape

output_height = image_height - kernel_height +1
output_width = image_width - kernel_width + 1

output = np.zeros(
    (output_height, output_width),
    dtype=np.float32
)

for i in range(output_height):
    for j in range(output_width):

        neighborhood = image[i:i+kernel_height, j:j+kernel_width]

        output[i, j] = np.sum(
            neighborhood * kernel
        )

print(output)

[[ 70.  80.  90.]
 [120. 130. 140.]
 [170. 180. 190.]]
