In [1]:
import numpy as np

image = np.array([
    [20,20,20,20,20],
    [20,20,255,20,20],
    [20,20,20,20,20],
    [20,20,20,20,20],
    [20,20,20,20,20]
], dtype=np.float32)

padded = np.pad(image, 1, mode="constant")

output = np.zeros_like(image)

for i in range(image.shape[0]):
    for j in range(image.shape[1]):
        neighborhood = padded[i:i+3, j:j+3]
        output[i,j] = np.median(neighborhood)

print(output)

[[ 0. 20. 20. 20.  0.]
 [20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]
 [ 0. 20. 20. 20.  0.]]
