<a href="https://colab.research.google.com/github/aashutoshraj521/Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Numpy Array ->> Printing

import numpy as np

a = np.array([1,2,3])
b = np.array([10,20,30])

print(a)
print(b)

[1 2 3]
[10 20 30]


In [3]:
type(np.array([1,2,3]))

numpy.ndarray

In [4]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(a + b)

[11 22 33]


In [5]:
# Shape of Array

x = np.array([
    [1,2,3],
    [4,5,6]
])
x.shape

(2, 3)

In [6]:
y = np.array([
    [
        [1,2,3],
        [4,5,6]
    ]
])
y.shape

(1, 2, 3)

In [7]:
z = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ],
    [
        [9,10],
        [11,12]
    ]
])
z.shape

(3, 2, 2)

In [8]:
# Indexing
c = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print(c[0][0][0], " and ",  c[1][1][1])

1  and  8


In [9]:
x = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])
print(x[0:2])

[[10 20 30 40]
 [50 60 70 80]]


In [10]:
# Reshaping
a = np.array([
    [1,2,3],
    [4,5,6]
])
a = a.reshape(6,)
print(a)

[1 2 3 4 5 6]


In [11]:
# Broadcasting

a = np.array([1,2,3])
print(a + 5)

[6 7 8]


In [12]:
a = np.array([1,2,3])
print(a * 10)

[10 20 30]


In [13]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(a + b)

[11 22 33]


In [15]:
# Creating Artificial Images

red = np.zeros((10,10,3)) + [255,0,0]
green = np.zeros((10,10,3)) + [0,255,0]
blue = np.zeros((10,10,3)) + [0,0,255]

print(red)
print(green)
print(blue)

[[[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0.   0.]
  [255.   0.   0.]
  

In [25]:
# type and dtype
img = np.array([255], dtype=np.uint8)
print(type(img))
img.dtype

<class 'numpy.ndarray'>


dtype('uint8')

In [23]:
img = img.astype(np.float32)
print(type(img))
img.dtype

<class 'numpy.ndarray'>


dtype('float32')