In [2]:
import numpy as np

image = np.array([
    [10,  20,  30,  40,  50],
    [60,  70,  80,  90, 100],
    [110, 120, 130, 140, 150],
    [160, 170, 180, 190, 200],
    [210, 220, 230, 240, 250]
], dtype=np.float32)

kernel = np.array([
    [0, 0, 0],
    [0, 1, 0],
    [0, 0, 0]
], dtype=np.float32)

In [3]:
image_height, image_width = image.shape

kernel_height, kernel_width = kernel.shape

output_height = image_height - kernel_height +1
output_width = image_width - kernel_width + 1

output = np.zeros(
    (output_height, output_width),
    dtype=np.float32
)

In [12]:
padding = 1

padded_image = np.pad(
    image,
    pad_width=padding,
    mode = "constant"
)

print(padded_image)
print(padded_image.shape)

[[  0.   0.   0.   0.   0.   0.   0.]
 [  0.  10.  20.  30.  40.  50.   0.]
 [  0.  60.  70.  80.  90. 100.   0.]
 [  0. 110. 120. 130. 140. 150.   0.]
 [  0. 160. 170. 180. 190. 200.   0.]
 [  0. 210. 220. 230. 240. 250.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]]
(7, 7)
